- name: Add lua plugin
  command: asdf plugin add lua
  register: lua_add
  failed_when: lua_add.rc not in [0, 2]

- name: Install lua versions
  command: asdf install lua {{item}}
  loop: "{{versions}}"
  register: lua_install
  failed_when: lua_install.rc != 0 and "is already installed" not in lua_install.stderr

- name: Set global version for lua to {{versions[0]}}
  command: "asdf set lua {{versions[0]}}"

- name: Record role in lockfile
  command: "{{ playbook_dir }}/bin/lock-role {{ ansible_role_name }}"
  changed_when: false
