- name: Install zsh
  homebrew:
    name: zsh

# Oh My ZSH
- name: Check for oh-my-zsh installation
  stat: "path=~/.oh-my-zsh"
  register: oh_my_zsh_stat
- name: Install oh-my-zsh
  raw: "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""
  when: not oh_my_zsh_stat.stat.exists

# Oh My ZSH - plugins
- name: Install syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
- name: Install auto-suggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

# ZSH Configuration
- name: Create config directory if it doesn't exist
  file:
    path: "{{ dotfiles_user_home }}/.config/zsh"
    state: directory
    mode: '0755'

- name: Symlink ZSH config files
  file:
    src: "{{ dotfiles_home }}/roles/zsh/files/"
    dest: "{{ dotfiles_user_home }}/.config/zsh"
    state: link
    force: yes

# ZSHRC
- name: Check for .zshrc
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat
- name: Back up .zshrc
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists
- name: Link .zshrc
  file:
    src: "{{ dotfiles_user_home }}/.config/zsh/zshrc"
    dest: "{{dotfiles_user_home}}/.zshrc"
    state: link
    force: yes
- name: Check for .zshenv
  stat: path="{{ dotfiles_user_home }}/.zshenv"
  register: zshenv_stat
- name: Back up .zshenv
  command: mv ~/.zshenv ~/.zshenv.bak
  args:
    creates: "{{ dotfiles_user_home }}/.zshenv.bak"
  when: zshenv_stat.stat.exists and not zshenv_stat.stat.islnk
- name: Link .zshenv
  file:
    src: "{{ dotfiles_user_home }}/.config/zsh/zshenv"
    dest: "{{ dotfiles_user_home }}/.zshenv"
    state: link
    force: yes

- name: Check for .zprofile
  stat: path="{{ dotfiles_user_home }}/.zprofile"
  register: zprofile_stat
- name: Back up .zprofile
  command: mv ~/.zprofile ~/.zprofile.bak
  args:
    creates: "{{ dotfiles_user_home }}/.zprofile.bak"
  when: zprofile_stat.stat.exists and not zprofile_stat.stat.islnk
- name: Link .zprofile
  file:
    src: "{{ dotfiles_user_home }}/.config/zsh/zprofile"
    dest: "{{ dotfiles_user_home }}/.zprofile"
    state: link
    force: yes

- name: Create hushlogin file
  file:
    src: "{{ dotfiles_user_home }}/.config/zsh/hushlogin"
    dest: "{{ dotfiles_user_home }}/.hushlogin"
    state: link
    force: yes

# prompt
- name: Install Starship prompt
  homebrew:
    name: starship

- name: Record role in lockfile
  command: "{{ playbook_dir }}/bin/lock-role {{ ansible_role_name }}"
  changed_when: false
