- name: Install cli tools
  homebrew:
    name: "{{item}}"
  loop: "{{tools}}"

- name: Install font
  homebrew_cask:
    name: font-hack-nerd-font

- name: Record role in lockfile
  command: "{{ playbook_dir }}/bin/lock-role {{ ansible_role_name }}"
  changed_when: false
